name: dart_tinydtls_libs_example
description: Demonstrates how to use the dart_tinydtls_libs plugin.

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dart_tinydtls_libs:
    path: ../

  cupertino_icons: ^1.0.2
  dart_tinydtls:
    git:
      url: https://github.com/namib-project/dart_tinydtls.git
      ref: regenerate-bindings

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
