name: dart_tinydtls_libs
description: Provides tinyDTLS binaries for adding DTLS support to Flutter apps.
version: 0.1.0
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: me.namib.dart_tinydtls_libs
        pluginClass: DartTinydtlsLibsPlugin
      linux:
        pluginClass: DartTinydtlsLibsPlugin
      windows:
        pluginClass: DartTinydtlsLibsPlugin
