name: Build Status

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-android:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Build Android App
      run: |
        cd example
        flutter pub get
        flutter build apk
        flutter build appbundle

  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Install dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ninja-build libgtk-3-dev
    - name: Build Linux App
      run: |
        cd example
        flutter build linux

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    - name: Build Windows App
      run: |
        cd example
        flutter build windows

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: flutter config --enable-macos-desktop
    - name: Build macOS App
      run: |
        cd example
        flutter build macos
    - run: ls -R
